### ISSUE TITLE
Missing a few files in git commit

### ISSUE THREAD

**Issue by ivawzh** [benawad/react-suspense-example#4]
Hi, thanks for the good work. Just FYI, I think you didn't add a few files in this git commit, like `BigPrime`, `MyButton`, `ErrorBoundary` etc

https://github.com/benawad/react-suspense-example/blob/cb133187d3b5b0a78fd71106d2fa37d1126f49a4/src/App.js#L2-L7

**Comment by benawad** [comment]
try changing branches

**Comment by ivawzh** [comment]
@benawad Got it. Sorry, Octotree is broken on branch.
